version: '3.7'
services:
    db:
      image: postgres:11
      environment:
        - POSTGRES_USER:postgres
        - POSTGRES_HOST_AUTH_METHOD:trust
        - POSTGRES_DB:healthcareresourcefinder
      ports:
        - "5432:5432"
      volumes:
        - ./docker/postgresql/data:/var/lib/postgresql/data