# Generated by Django 3.0.4 on 2020-05-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_formsubmissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmissions',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
