# Generated by Django 3.0.4 on 2020-05-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200502_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmissions',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
