# Generated by Django 3.0.4 on 2020-05-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'demographics',
            },
        ),
        migrations.CreateModel(
            name='MedProvider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=5000)),
                ('id_demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Demographics')),
            ],
            options={
                'db_table': 'medprovider',
            },
        ),
        migrations.CreateModel(
            name='CHCProvider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('facilityname', models.CharField(max_length=250)),
                ('specialty', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('id_demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Demographics')),
            ],
            options={
                'db_table': 'chcprovider',
            },
        ),
        migrations.CreateModel(
            name='BHProvider',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('facilityname', models.CharField(max_length=250)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('id_demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Demographics')),
            ],
            options={
                'db_table': 'bhprovider',
            },
        ),
    ]
