# Generated by Django 3.0.4 on 2020-05-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'demographics',
            },
        ),
        migrations.CreateModel(
            name='MedProviders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=5000)),
                ('demo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Demographics')),
            ],
            options={
                'db_table': 'medproviders',
            },
        ),
        migrations.CreateModel(
            name='CHCProviders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('facilityname', models.CharField(max_length=250)),
                ('specialty', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('demo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Demographics')),
            ],
            options={
                'db_table': 'chcproviders',
            },
        ),
        migrations.CreateModel(
            name='BHProviders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('facilityname', models.CharField(max_length=250)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('demo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Demographics')),
            ],
            options={
                'db_table': 'bhproviders',
            },
        ),
    ]
