# Generated by Django 3.0.4 on 2020-05-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bhprovider',
            old_name='id_demo',
            new_name='demo',
        ),
        migrations.RenameField(
            model_name='chcprovider',
            old_name='id_demo',
            new_name='demo',
        ),
        migrations.RenameField(
            model_name='medprovider',
            old_name='id_demo',
            new_name='demo',
        ),
    ]
