# Generated by Django 3.0.4 on 2020-05-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bhproviders',
            table='bhprovider',
        ),
        migrations.AlterModelTable(
            name='chcproviders',
            table='chcprovider',
        ),
        migrations.AlterModelTable(
            name='medproviders',
            table='medprovider',
        ),
    ]
