# Generated by Django 3.0.4 on 2020-05-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200501_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bhproviders',
            old_name='demo_id',
            new_name='id_demo',
        ),
        migrations.RenameField(
            model_name='chcproviders',
            old_name='demo_id',
            new_name='id_demo',
        ),
        migrations.RenameField(
            model_name='medproviders',
            old_name='demo_id',
            new_name='id_demo',
        ),
    ]
