# Generated by Django 3.0.4 on 2020-05-02 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_auto_20200501_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhproviders',
            name='id_demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Demographics'),
        ),
        migrations.AlterField(
            model_name='chcproviders',
            name='id_demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Demographics'),
        ),
        migrations.AlterField(
            model_name='medproviders',
            name='id_demo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Demographics'),
        ),
    ]
