# Generated by Django 3.0.4 on 2020-05-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20200501_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BHProviders',
        ),
    ]
