# Generated by Django 3.0.4 on 2020-05-02 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_delete_bhproviders'),
    ]

    operations = [
        migrations.CreateModel(
            name='BHProviders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('facilityname', models.CharField(max_length=250)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('id_demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Demographics')),
            ],
            options={
                'db_table': 'bhprovider',
            },
        ),
    ]
