# Generated by Django 3.0.4 on 2020-05-02 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_bhproviders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chcproviders',
            name='id_demo',
        ),
        migrations.RemoveField(
            model_name='medproviders',
            name='id_demo',
        ),
        migrations.DeleteModel(
            name='BHProviders',
        ),
        migrations.DeleteModel(
            name='CHCProviders',
        ),
        migrations.DeleteModel(
            name='MedProviders',
        ),
    ]
