# Generated by Django 3.0.4 on 2020-05-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20200501_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bhproviders',
            old_name='id_demo',
            new_name='demo',
        ),
        migrations.RenameField(
            model_name='chcproviders',
            old_name='id_demo',
            new_name='demo',
        ),
        migrations.RenameField(
            model_name='medproviders',
            old_name='id_demo',
            new_name='demo',
        ),
        migrations.AlterField(
            model_name='demographics',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
